#!/bin/bash
# AppArmor Profile Management Tool
# Generated by system-setup.sh

usage() {
    echo "Usage: $0 {status|complain|enforce|new-profile|monitor} [profile]"
    echo ""
    echo "Commands:"
    echo "  status              - Show AppArmor status"
    echo "  complain <profile>  - Set profile to complain mode"
    echo "  enforce <profile>   - Set profile to enforce mode"
    echo "  new-profile <cmd>   - Generate new profile for command"
    echo "  monitor             - Monitor AppArmor denials"
    exit 1
}

case "$1" in
    status)
        aa-status
        ;;
    complain)
        [[ -n "$2" ]] && aa-complain "$2" || echo "Profile required"
        ;;
    enforce)
        [[ -n "$2" ]] && aa-enforce "$2" || echo "Profile required"
        ;;
    new-profile)
        [[ -n "$2" ]] && aa-genprof "$2" || echo "Command required"
        ;;
    monitor)
        journalctl -f | grep -i apparmor
        ;;
    *)
        usage
        ;;
esac