#!/bin/bash
# AppArmor Status Report
# Generated by system-setup.sh

echo "=== AppArmor Status Report $(date) ==="
echo ""

echo "AppArmor Module Status:"
aa-status | head -10

echo ""
echo "Recent Denials (last 24 hours):"
journalctl --since "24 hours ago" | grep -i "apparmor.*denied" | tail -10 || echo "No recent denials"

echo ""
echo "Profiles in Complain Mode:"
aa-status | grep -A 100 "profiles are in complain mode" | tail -n +2 | head -20 || echo "None"

echo ""
echo "Available Profiles Not Loaded:"
find /etc/apparmor.d -name "usr.*" -type f | while read profile; do
    basename "$profile"
done | sort | head -10